services:
  - type: web
    name: slope-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: LINE_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false
      - key: LINE_USER_ID2
        sync: false
      - key: FRED_API_KEY
        sync: false
